global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
# — “first.rules”
# — “second.rules”
scrape_configs:
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000
          - host.docker.internal:9090